export const TEXT_COLORS = {
  WINNER_CHANCE: '#717171',
  PRICE: '#74727A',
  GOLD: '#FFD700',
  LIGHT_BLUE: '#B8F0FF',
  GRAY: '#413E48',
};

export const BUTTON_COLORS = {
  LOGIN: '#164ECE',
  LOTTO: '#F7F5FA',
  EXTRA_LOTTO: '#E6E4EC',
};

export const COLORS = {
  WHITE: '#FFFFFF',
  RED: '#C22E44',
  PRIMARY_BACKGROUND: '#F7F5FA',
};
